<a href="https://colab.research.google.com/github/rinviriti/AI-ML-Learning-Journey/blob/main/06_numpy_pandas/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Summary

In this notebook I learned:

- Creating NumPy arrays
- Understanding array shape
- Understanding dimensions
- Understanding data types
- Creating arrays of zeros and ones

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)

Shape: (5,)
Dimensions: 1
Data Type: int64


In [ ]:
zeros = np.zeros((2,3))
ones = np.ones((2,3))

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
